using Aiursoft.GeminiBot.Models;
using Aiursoft.NugetNinja.GitServerBase.Models;
using Aiursoft.NugetNinja.GitServerBase.Services;
using Aiursoft.NugetNinja.GitServerBase.Services.Providers;
using Microsoft.Extensions.Logging;

namespace Aiursoft.GeminiBot.Services;

/// <summary>
/// Encapsulates the business logic for processing GitLab issues.
/// </summary>
public class IssueProcessor(
    IVersionControlService versionControl,
    BotWorkflowEngine workflowEngine,
    HttpWrapper httpWrapper,
    ILogger<IssueProcessor> logger)
{
    public async Task<ProcessResult> ProcessAsync(Issue issue, Server server)
    {
        try
        {
            ValidateIssue(issue);
            logger.LogInformation("Analyzing Issue #{IssueId}: {Title} on {EndPoint} (Project ID: {ProjectId})...",
                issue.Iid, issue.Title, server.EndPoint, issue.ProjectId);

            // Fetch repository details as early as possible for better logging and context.
            var repository = await versionControl.GetRepository(
                server.EndPoint,
                issue.ProjectId.ToString(),
                string.Empty,
                server.Token);

            logger.LogInformation("Working on repository: {RepoName} ({RepoUrl})",
                repository.Name, repository.CloneUrl);

            if (await versionControl.HasOpenPullRequestForIssue(server.EndPoint, issue.ProjectId, issue.Iid, server.Token))
            {
                logger.LogInformation("Issue #{IssueId} already has an open PR/MR. Skipping to avoid duplicate work.", issue.Iid);
                return ProcessResult.Skipped("Issue already has an open PR/MR");
            }

            if (!await IsIssueOpenAsync(server, issue))
            {
                logger.LogInformation("Issue #{IssueId} is already closed. Skipping.", issue.Iid);
                return ProcessResult.Skipped("Issue is already closed");
            }

            logger.LogInformation("Issue #{IssueId} needs attention. Bot will create a fork and a new MR.", issue.Iid);

            var defaultBranch = repository.DefaultBranch ?? "master"; // Fallback to master if null

            var comments = await GetIssueCommentsAsync(server, issue);
            var context = new WorkflowContext
            {
                Server = server,
                ProjectId = issue.ProjectId.ToString(),
                SourceBranch = defaultBranch, // Use repository's default branch
                TargetBranch = defaultBranch,
                WorkspaceName = $"issue-{issue.Iid}",
                Prompt = BuildTaskDescription(issue, comments),
                CommitMessage = $"Fix for issue #{issue.Iid}: {issue.Title}\n\nAutomatically generated by Gemini Bot.",
                PushBranch = $"fix-issue-{issue.Iid}",
                HideGitFolder = true
            };

            await workflowEngine.ExecuteAsync(context, async ctx =>
            {
                await workflowEngine.EnsureRepositoryForkedAsync(server, ctx.Repository!);
                var pushPath = versionControl.GetPushPath(server, ctx.Repository!);
                try
                {
                    await workflowEngine.PushAndFinalizeAsync(ctx, pushPath);
                }
                catch (Exception ex) when (server.Provider == "GitLab")
                {
                    var repoName = ctx.Repository!.Name ?? throw new InvalidOperationException("Repository name is null");
                    logger.LogWarning(ex, "Push failed for issue #{IssueId}. Deleting broken fork {UserName}/{RepoName} so it will be re-forked on next cycle.",
                        issue.Iid, server.UserName, repoName);
                    try
                    {
                        var projectPath = Uri.EscapeDataString($"{server.UserName}/{repoName}");
                        var deleteUrl = $"{server.EndPoint.TrimEnd('/')}/api/v4/projects/{projectPath}";
                        await httpWrapper.SendHttpAndGetJson<object>(deleteUrl, HttpMethod.Delete, server.Token);
                        logger.LogInformation("Successfully deleted broken fork: {UserName}/{RepoName}", server.UserName, repoName);
                    }
                    catch (Exception deleteEx)
                    {
                        logger.LogError(deleteEx, "Failed to delete broken fork {UserName}/{RepoName}", server.UserName, repoName);
                    }
                    throw;
                }

                if (await IsIssueOpenAsync(server, issue))
                {
                    await CreatePullRequestIfNeededAsync(server, ctx.Repository!, issue, ctx.PushBranch, ctx.GeminiOutput);
                }
                else
                {
                    logger.LogWarning("Issue #{IssueId} has been closed while processing. Skipping pull request creation.", issue.Iid);
                }
            });

            return context.Result;
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Error processing issue #{IssueIid}", issue.Iid);
            return ProcessResult.Failed($"Error processing issue #{issue.Iid}", ex);
        }
    }

    private async Task<string> GetIssueCommentsAsync(Server server, Issue issue)
    {
        if (server.Provider != "GitLab")
        {
            return string.Empty;
        }

        try
        {
            var url = $"{server.EndPoint.TrimEnd('/')}/api/v4/projects/{issue.ProjectId}/issues/{issue.Iid}/notes?sort=asc&order_by=created_at";
            var notes = await httpWrapper.SendHttpAndGetJson<List<GitLabNote>>(url, HttpMethod.Get, server.Token);

            var comments = notes
                .Where(n => !n.System)
                .Select(n => $"Comment by @{n.Author.Username} at {n.Created_at:yyyy-MM-dd HH:mm:ss}:\n{n.Body}")
                .ToList();

            return comments.Any() ? "\n\n## Issue Comments\n" + string.Join("\n\n---\n\n", comments) : string.Empty;
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "Failed to fetch comments for issue #{IssueId}", issue.Iid);
            return string.Empty;
        }
    }

    private async Task<bool> IsIssueOpenAsync(Server server, Issue issue)
    {
        if (server.Provider != "GitLab")
        {
            // For other providers, we don't have a direct way to check yet via IVersionControlService.
            // We assume it's still open to avoid breaking existing functionality for other providers.
            return true;
        }

        try
        {
            var url = $"{server.EndPoint.TrimEnd('/')}/api/v4/projects/{issue.ProjectId}/issues/{issue.Iid}";
            var issueDetails = await httpWrapper.SendHttpAndGetJson<GitLabIssueDto>(url, HttpMethod.Get, server.Token);
            return string.Equals(issueDetails.State, "opened", StringComparison.OrdinalIgnoreCase);
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "Failed to check if issue #{IssueId} is still open. Assuming it is.", issue.Iid);
            return true;
        }
    }

    private void ValidateIssue(Issue issue)
    {
        if (string.IsNullOrWhiteSpace(issue.Title))
            throw new ArgumentException($"Issue {issue.Id} has no title", nameof(issue));
        if (issue.ProjectId <= 0)
            throw new ArgumentException($"Issue {issue.Id} has invalid project ID", nameof(issue));
    }

    private string BuildTaskDescription(Issue issue, string comments)
    {
        return $"Issue #{issue.Iid}: {issue.Title}\n\n{issue.Description ?? "No description provided."}{comments}\n\nPlease analyze this issue and make the necessary code changes to resolve it.\n\nDon't forget to bump the version for updated nuget package projects after necessary changes, while do NOT add a version tag for projects doesn't publish nuget packages!";
    }

    private async Task CreatePullRequestIfNeededAsync(Server server, Repository repository, Issue issue, string branchName, string geminiOutput)
    {
        var ownerLogin = repository.Owner?.Login ?? throw new InvalidOperationException("Repository owner is null");
        var repoName = repository.Name ?? throw new InvalidOperationException("Repository name is null");
        var defaultBranch = repository.DefaultBranch ?? throw new InvalidOperationException("Repository default branch is null");

        var existingPullRequestsByBot = (await versionControl.GetPullRequests(
                server.EndPoint,
                ownerLogin,
                repoName,
                $"{server.UserName}:{branchName}",
                server.Token))
            .Where(p => string.Equals(p.User?.Login, server.UserName, StringComparison.OrdinalIgnoreCase));

        if (existingPullRequestsByBot.All(p => p.State != "open"))
        {
            logger.LogInformation("Creating pull request for issue #{IssueId}...", issue.Iid);

            var title = $"Fix for issue #{issue.Iid}: {issue.Title}";
            var body = $@"
Automatically generated by Gemini Bot to fix issue #{issue.Iid}.

Closes #{issue.Iid}

## Issue
{issue.Title}

{issue.Description ?? "No description provided."}

## Changes
This pull request contains automated fixes generated by the Gemini Bot.

## Gemini CLI Context
```
{geminiOutput}
```

Please review carefully before merging.";

            try
            {
                await versionControl.CreatePullRequest(
                    server.EndPoint,
                    ownerLogin,
                    repoName,
                    $"{server.UserName}:{branchName}",
                    defaultBranch,
                    title,
                    body,
                    server.Token);
            }
            catch (HttpRequestException ex) when (ex.StatusCode == System.Net.HttpStatusCode.UnprocessableEntity)
            {
                // If the fork is too old or detached, GitLab returns 422 Unprocessable Entity ("Source project is not a fork of the target project").
                // We directly delete the remote forked project here, so it can be re-forked and retried in the next run.
                logger.LogWarning(ex, "Failed to create pull request for issue #{IssueId}. The fork might be too old or detached. Deleting the remote fork...", issue.Iid);

                if (server.Provider == "GitLab")
                {
                    try
                    {
                        var projectPath = Uri.EscapeDataString($"{server.UserName}/{repoName}");
                        var deleteUrl = $"{server.EndPoint.TrimEnd('/')}/api/v4/projects/{projectPath}";
                        await httpWrapper.SendHttpAndGetJson<object>(deleteUrl, HttpMethod.Delete, server.Token);
                        logger.LogInformation("Successfully deleted the remote fork: {ProjectPath}", projectPath);
                    }
                    catch (Exception deleteEx)
                    {
                        logger.LogError(deleteEx, "Failed to delete the remote fork after pull request creation failed.");
                    }
                }

                throw;
            }

            if (server.Provider == "GitLab")
            {
                await AssignBotToGitLabMr(server, issue, branchName);
            }
        }
    }

    private async Task AssignBotToGitLabMr(Server server, Issue issue, string branchName)
    {
        try
        {
            var userUrl = $"{server.EndPoint.TrimEnd('/')}/api/v4/user";
            var user = await httpWrapper.SendHttpAndGetJson<GitLabUser>(userUrl, HttpMethod.Get, server.Token);

            var mrUrl = $"{server.EndPoint.TrimEnd('/')}/api/v4/projects/{issue.ProjectId}/merge_requests?state=opened&source_branch={branchName}";
            var mrs = await httpWrapper.SendHttpAndGetJson<List<GitLabMergeRequestDto>>(mrUrl, HttpMethod.Get, server.Token);
            var mr = mrs.FirstOrDefault();

            if (mr != null)
            {
                var updateUrl = $"{server.EndPoint.TrimEnd('/')}/api/v4/projects/{issue.ProjectId}/merge_requests/{mr.Iid}?assignee_id={user.Id}";
                await httpWrapper.SendHttpAndGetJson<object>(updateUrl, HttpMethod.Put, server.Token);
                logger.LogInformation("Assigned MR #{IID} to bot user {UserName}", mr.Iid, server.UserName);
            }
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to assign MR to bot for issue #{IssueId}", issue.Iid);
        }
    }
}
